### ISSUE TITLE
Fabric?

### ISSUE THREAD

**Issue by TheArcaneBrony** [SaishoVibes/Back-in-Classic#20]
You should port this mod to fabric, where it can enjoy being combined with a bunch of retro mods!

**Comment by SaishoVibes** [comment]
Hi, I have had finals and stuff. Let me look st downloading fabric and I will try for a 1.16.5 Fabric Version

**Comment by SaishoVibes** [comment]
Moving 0.8.0 to Fabric.

[https://github.com/SaishoVibes/Back-in-Classic-Fabric](https://github.com/SaishoVibes/Back-in-Classic-Fabric)
